// <auto-generated />
using System;
using Backend_Exam_Project.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Backend_Exam_Project.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260224043451_addedAssigntToForeiginKey")]
    partial class addedAssigntToForeiginKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            // Identity columns handled by PostgreSQL provider (Npgsql)

            modelBuilder.Entity("Backend_Exam_Project.Models.Roles", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Identity handled by Npgsql

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RoleID");

                    b.HasIndex("RoleName")
                        .IsUnique();

                    b.ToTable("Roles", t =>
                        {
                            t.HasCheckConstraint("CK_Roles_RoleName", "RoleName IN ('Manager','Support','User')");
                        });
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.TicketComments", b =>
                {
                    b.Property<int>("TicketCommentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Identity handled by Npgsql

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CommentedByID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicktID")
                        .HasColumnType("int");

                    b.HasKey("TicketCommentID");

                    b.HasIndex("CommentedByID");

                    b.HasIndex("TicktID");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.TicketStatusLogs", b =>
                {
                    b.Property<int>("TicketStatusLogID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Identity handled by Npgsql

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ChangedByID")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketID")
                        .HasColumnType("int");

                    b.HasKey("TicketStatusLogID");

                    b.HasIndex("ChangedByID");

                    b.ToTable("TicketStatusLogs", t =>
                        {
                            t.HasCheckConstraint("CK_TicketStatusLogs_NewStatus", "NewStatus IN ('Open','In Progress','Resolved', 'Closed')");

                            t.HasCheckConstraint("CK_TicketStatusLogs_OldStatus", "OldStatus IN ('Open','In Progress','Resolved', 'Closed')");
                        });
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.Tickets", b =>
                {
                    b.Property<int>("TicketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Identity handled by Npgsql

                    b.Property<int>("AssignedTo")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Medium");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Open");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TicketID");

                    b.HasIndex("AssignedTo");

                    b.HasIndex("CreatedBy");

                    b.ToTable("Tickets", t =>
                        {
                            t.HasCheckConstraint("CK_Tickets_Priority", "Priority IN ('Low','Medium','High')");

                            t.HasCheckConstraint("CK_Tickets_Status", "Status IN ('Open','In Progress','Resolved', 'Closed')");
                        });
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.Users", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    // Identity handled by Npgsql

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(555)
                        .HasColumnType("nvarchar(555)");

                    b.Property<int>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleID");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.TicketComments", b =>
                {
                    b.HasOne("Backend_Exam_Project.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("CommentedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend_Exam_Project.Models.Tickets", "Tickets")
                        .WithMany()
                        .HasForeignKey("TicktID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.TicketStatusLogs", b =>
                {
                    b.HasOne("Backend_Exam_Project.Models.Users", "Users")
                        .WithMany()
                        .HasForeignKey("ChangedByID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.Tickets", b =>
                {
                    b.HasOne("Backend_Exam_Project.Models.Users", "AssignedUser")
                        .WithMany()
                        .HasForeignKey("AssignedTo")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Backend_Exam_Project.Models.Users", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AssignedUser");

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("Backend_Exam_Project.Models.Users", b =>
                {
                    b.HasOne("Backend_Exam_Project.Models.Roles", "Roles")
                        .WithMany()
                        .HasForeignKey("RoleID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
